services:
  bot:
    build:
      context: .
    container_name: language_practice_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - HASH_SALT=${HASH_SALT}
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - pg
    volumes:
      - .:/app
    restart: always

  pg:
    image: postgres:15
    container_name: language_practice_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
